variable "aws_region" { type = string default = "us-east-1" }
variable "project_name" { type = string default = "ecs-demo" }
variable "environment" { type = string default = "dev" }
variable "vpc_cidr" { type = string default = "10.20.0.0/16" }
variable "container_port" { type = number default = 8080 }
variable "task_cpu" { type = number default = 256 }
variable "task_memory" { type = number default = 512 }
variable "desired_count" { type = number default = 2 }
variable "min_capacity" { type = number default = 2 }
variable "max_capacity" { type = number default = 4 }
variable "container_image" { type = string default = "" }
